site_name: Мій конспект...
site_url: https://BatyrbekCherushev.github.io/STUDY_NOTES/
repo_url: https://github.com/BatyrbekCherushev/STUDY_NOTES



nav:
- Головна: index.md
- MKDOCS: 
  - Autodeploy to GitHub pages: MKDOCS/mkdocs_autodeploy_setup.md
  - MkDocs commnds: MKDOCS/mkdocs_commands.md

- КОМП'ЮТЕРНІ НАУКИ:
  - Алгоритми і структури даних: CS/cs_algorithms_data_structures.md
  - Комп'ютерні мережі: CS/cs_networks.md
  - HTTP: CS/cs_http.md

- PYTHON: 
  - Корисні посилання: PYTHON/python_links.md
  - Змінні: PYTHON/python_variables.md
  - Типи даних: PYTHON/python_types.md
  - Оператори: PYTHON/python_operators.md
  - Exceptions: PYTHON/python_exceptions.md
  - Простір імен, область видимості: PYTHON/python_namespace_scope.md
  - Класи: PYTHON/python_classes.md
  - Ітератори. генератори: PYTHON/python_iterator_generators.md
  - Контекстні менеджери: PYTHON/python_context_managers.md
  - Мережеве програмування: PYTHON/python_network_programming.md
  - Бібліотека requests: PYTHON/python_requests.md

- GIT:
  - Корисні посилання: GIT/git_links.md
  - Основні поняття GIT: GIT/git_definitions.md
  - Термінологія GIT: GIT/terminology.md
  - Основні команди GIT: GIT/git_basic_commands.md

- Корисні посилання:
  - ЗАГАЛЬНЕ: LINKS/links_basic.md
  - ENGLISH: LINKS/links_english.md
  - ІНФОРМАТИКА: LINKS/links_cs.md
  - ІНСТРУМЕНТИ : LINKS/links_tools.md
  - ВАЖЛИВІ БАЗОВІ ТЕМИ: LINKS/links_important_subjects.md
  - БАЗИ ДАНИХ: LINKS/links_databases.md
  - РОБОЧИЙ ПРОЦЕС: LINKS/links_workflow.md


theme:
  name: material
  favicon: RES/img/logo.svg
  language: uk
  features:
    - search.highlight
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - navigation.tabs          # вкладки зверху
    - navigation.tabs.sticky   # вкладки "приклеєні"
    - navigation.sections      # секції в сайдбарі
    - navigation.expand        # можна розгортати підрозділи
    - navigation.collapse      # підрозділи за замовчуванням згорнуті
  navigation_depth: 3
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Темний
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Світлий

# theme:
#   name: material
#   favicon: RES/img/logo.svg
#   language: uk
#   features:
#     - search.highlight
#     - navigation.footer
#     - navigation.instant
#     - navigation.tracking
#     - navigation.indexes
#     - navigation.top
#     - navigation.sections
#     - navigation.expand
#     - navigation.collapse
#   navigation_depth: 3
#   palette: 
#     - scheme: default
#       toggle:
#         icon: material/brightness-7 
#         name: Темний
#     - scheme: slate
#       toggle:
#         icon: material/brightness-4
#         name: Світлий

# theme:
#   name: material
#   favicon: RES/img/logo.svg
#   language: uk
#   features:
#     - search.highlight
#     - navigation.footer
#     - navigation.instant # ускорение загрузки (SPA)
#     - navigation.tracking # динамический URL страницы 
#     - navigation.tabs # перенос названий документов в горизонтальное меню
#     - navigation.tabs.sticky # горизонтальное меню не скрывается при прокрутке
#     - navigation.indexes # главные страницы разделов не отображаются в меню
#     - navigation.top # вкл. кнопку возврата наверх
#     - navigation.expand          # щоб підрозділи розкривалися
#     - navigation.collapse        # щоб підрозділи за замовчуванням були приховані
#   palette: 
#     - scheme: default
#       toggle:
#         icon: material/brightness-7 
#         name: Темний
#     - scheme: slate
#       toggle:
#         icon: material/brightness-4
#         name: Світлий
